Database performance
nevisende/vet-clinic pull request #5
Opened 2022-02-21 13:00 UTC by Chimwemwe-127001

## Database performance
> In this feature update:
- `SELECT COUNT(*) FROM visits where animal_id = 4;`

   ![visits-animal-id](https://user-images.githubusercontent.com/52143815/154959431-58877132-62c9-46c1-a4cb-9cc97554edbb.png)
- `SELECT * FROM visits where vet_id = 2;`

   ![visits-vets-id](https://user-images.githubusercontent.com/52143815/154959886-4b3dd715-558b-4e78-8e13-ff53797ccda3.png)

- `SELECT * FROM owners where email = 'owner_18327@mail.com';`

   ![owners-email](https://user-images.githubusercontent.com/52143815/154959908-d1a97118-be19-40e7-a4a9-b5c324316e86.png)

### Our execution time of all instances were less than 1000 ms

2022-02-21 13:18 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi team, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
README is professional. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-21 13:18 UTC, SajjadAhmad14 commented on queries.sql
> +
Please add indexes to foreign keys to increase the queries performance.

2022-02-21 13:18 UTC, SajjadAhmad14 commented on queries.sql
> +
Please add pair of screenshots in the PR description with the results of the  `EXPLAIN ANALYZE` command for each of the above queries (in total it should be 6 screenshots).
The first screenshot should show how much time the query takes BEFORE adding indexes on foreign keys.
The second screenshot should show how much time the query takes AFTER the improvements introduced

2022-02-21 13:44 UTC, nevisende commented on queries.sql
> +
Please check my codes I have already added Foreign keys so we haven't anythings to add. And If ypu check the screenshots you can see our execution time is really good

2022-02-21 13:56 UTC, SajjadAhmad14 commented on queries.sql
> +
Hi, so the recommended solution is to add `Indexes` on foreign keys. Moreover, please add two screenshots for each query so they should be 6 in total.

2022-02-22 08:04 UTC, AshakaE approved these changes
### Hi @Chimwemwe-127001 & @SajjadAhmad14   🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 10:21 UTC, merged